export const paths = {
  dashboard: "/",
  messageTemplate: "/message-template",
  addNew: "/add-new",
  contact: "/contact",
  addNewContact: "/add-new-contact",
  listTags: "/list-tags",
  importExport: "/import-export",
  notification: "/notification",
  addNewNotification: "/add-new-notification",
  analyticsMessaging: "/analytics-messaging",
  analyticsNotifications: "/analytics-notifications",
  analyticsMessageTemplates: "/analytics-message-templates",
  basic: "/basic",
  automationAutoReplies: "/automation-auto-replies",
  inbox: "/inbox",
  createGroup: "/create-group",
  listGroups: "/list-groups",
  groupListNotification: "/group-list-notification",
  groupSendMessage: "/group-send-message",
  createTemplateGroup: "/create-template-group",
  subscriptionPlan: "/subscription-plan",
};
